version: '3.4'

services:
  redisdb:
    image: redis:alpine

  bagroup.api:
    image: ${DOCKER_REGISTRY-}bagroupapi
    build:
      context: ..
      dockerfile: BAGroup.API/Dockerfile

  reportdatagrpcservice:
    image: ${DOCKER_REGISTRY-}reportdatagrpcservice
    build:
      context: ..
      dockerfile: BA-API/ReportDataGrpcService/Dockerfile


  reportspeedover.api:
    image: ${DOCKER_REGISTRY-}reportspeedoverapi
    build:
      context: ..
      dockerfile: VehicleInformation/Dockerfile

  ocelotgateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: OcelotGateway/Dockerfile




